// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping_3d/pose_graph/proto/constraint_builder_self_adjust.proto

#ifndef PROTOBUF_cartographer_2fmapping_5f3d_2fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5fself_5fadjust_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_5f3d_2fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5fself_5fadjust_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace mapping_3d {
namespace pose_graph {
namespace proto {
class ConstraintBuilderSelfAdjust;
class ConstraintBuilderSelfAdjustDefaultTypeInternal;
extern ConstraintBuilderSelfAdjustDefaultTypeInternal _ConstraintBuilderSelfAdjust_default_instance_;
}  // namespace proto
}  // namespace pose_graph
}  // namespace mapping_3d
}  // namespace cartographer

namespace cartographer {
namespace mapping_3d {
namespace pose_graph {
namespace proto {

namespace protobuf_cartographer_2fmapping_5f3d_2fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5fself_5fadjust_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fmapping_5f3d_2fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5fself_5fadjust_2eproto

// ===================================================================

class ConstraintBuilderSelfAdjust : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust) */ {
 public:
  ConstraintBuilderSelfAdjust();
  virtual ~ConstraintBuilderSelfAdjust();

  ConstraintBuilderSelfAdjust(const ConstraintBuilderSelfAdjust& from);

  inline ConstraintBuilderSelfAdjust& operator=(const ConstraintBuilderSelfAdjust& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConstraintBuilderSelfAdjust(ConstraintBuilderSelfAdjust&& from) noexcept
    : ConstraintBuilderSelfAdjust() {
    *this = ::std::move(from);
  }

  inline ConstraintBuilderSelfAdjust& operator=(ConstraintBuilderSelfAdjust&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConstraintBuilderSelfAdjust& default_instance();

  static inline const ConstraintBuilderSelfAdjust* internal_default_instance() {
    return reinterpret_cast<const ConstraintBuilderSelfAdjust*>(
               &_ConstraintBuilderSelfAdjust_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ConstraintBuilderSelfAdjust* other);
  friend void swap(ConstraintBuilderSelfAdjust& a, ConstraintBuilderSelfAdjust& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConstraintBuilderSelfAdjust* New() const PROTOBUF_FINAL { return New(NULL); }

  ConstraintBuilderSelfAdjust* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConstraintBuilderSelfAdjust& from);
  void MergeFrom(const ConstraintBuilderSelfAdjust& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConstraintBuilderSelfAdjust* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool enabled = 1;
  void clear_enabled();
  static const int kEnabledFieldNumber = 1;
  bool enabled() const;
  void set_enabled(bool value);

  // float max_score = 2;
  void clear_max_score();
  static const int kMaxScoreFieldNumber = 2;
  float max_score() const;
  void set_max_score(float value);

  // float min_score = 3;
  void clear_min_score();
  static const int kMinScoreFieldNumber = 3;
  float min_score() const;
  void set_min_score(float value);

  // float step = 4;
  void clear_step();
  static const int kStepFieldNumber = 4;
  float step() const;
  void set_step(float value);

  // float too_few_percentage = 5;
  void clear_too_few_percentage();
  static const int kTooFewPercentageFieldNumber = 5;
  float too_few_percentage() const;
  void set_too_few_percentage(float value);

  // float too_many_percentage = 6;
  void clear_too_many_percentage();
  static const int kTooManyPercentageFieldNumber = 6;
  float too_many_percentage() const;
  void set_too_many_percentage(float value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool enabled_;
  float max_score_;
  float min_score_;
  float step_;
  float too_few_percentage_;
  float too_many_percentage_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_5f3d_2fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5fself_5fadjust_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConstraintBuilderSelfAdjust

// bool enabled = 1;
inline void ConstraintBuilderSelfAdjust::clear_enabled() {
  enabled_ = false;
}
inline bool ConstraintBuilderSelfAdjust::enabled() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.enabled)
  return enabled_;
}
inline void ConstraintBuilderSelfAdjust::set_enabled(bool value) {
  
  enabled_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.enabled)
}

// float max_score = 2;
inline void ConstraintBuilderSelfAdjust::clear_max_score() {
  max_score_ = 0;
}
inline float ConstraintBuilderSelfAdjust::max_score() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.max_score)
  return max_score_;
}
inline void ConstraintBuilderSelfAdjust::set_max_score(float value) {
  
  max_score_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.max_score)
}

// float min_score = 3;
inline void ConstraintBuilderSelfAdjust::clear_min_score() {
  min_score_ = 0;
}
inline float ConstraintBuilderSelfAdjust::min_score() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.min_score)
  return min_score_;
}
inline void ConstraintBuilderSelfAdjust::set_min_score(float value) {
  
  min_score_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.min_score)
}

// float step = 4;
inline void ConstraintBuilderSelfAdjust::clear_step() {
  step_ = 0;
}
inline float ConstraintBuilderSelfAdjust::step() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.step)
  return step_;
}
inline void ConstraintBuilderSelfAdjust::set_step(float value) {
  
  step_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.step)
}

// float too_few_percentage = 5;
inline void ConstraintBuilderSelfAdjust::clear_too_few_percentage() {
  too_few_percentage_ = 0;
}
inline float ConstraintBuilderSelfAdjust::too_few_percentage() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.too_few_percentage)
  return too_few_percentage_;
}
inline void ConstraintBuilderSelfAdjust::set_too_few_percentage(float value) {
  
  too_few_percentage_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.too_few_percentage)
}

// float too_many_percentage = 6;
inline void ConstraintBuilderSelfAdjust::clear_too_many_percentage() {
  too_many_percentage_ = 0;
}
inline float ConstraintBuilderSelfAdjust::too_many_percentage() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.too_many_percentage)
  return too_many_percentage_;
}
inline void ConstraintBuilderSelfAdjust::set_too_many_percentage(float value) {
  
  too_many_percentage_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_3d.pose_graph.proto.ConstraintBuilderSelfAdjust.too_many_percentage)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace pose_graph
}  // namespace mapping_3d
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_5f3d_2fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5fself_5fadjust_2eproto__INCLUDED
